### ISSUE TITLE
New blog posts are created with the wrong date format

### ISSUE THREAD

**Issue by dmackca** [Knogobert/ntn-boilerplate#123]
As per the [Netlify CMS docs](https://www.netlifycms.org/docs/widgets/#datetime), the dateTime widget needs a `format` property to define the storage date format. 
Without this, I think it just slugifies your locale's date object.

I tried it out and it ended up with this in the frontmatter:
```
createdAt: 2022-05-29T09:51:20.960Z
```
When I would have expected just the date part:
```
createdAt: 2022-05-29
```

And so the file was created with the name `blog/2022-05-29t09-51-20-960z-a-new-blog-post.md` where it should have been `blog/2022-05-29-a-new-blog-post.md`

**Comment by Knogobert** [comment]
Thanks for pointing this out, sorry I've been so tardy with fixing it. 

I added `format: "YYYY-MM-DD"` to the blog posts datetime picker.

Should now be fixed in the next release!
