### ISSUE TITLE
### [3.0.0]

### ISSUE THREAD

**Issue by Knogobert** [Knogobert/ntn-boilerplate#160]
### [3.0.0]

- [x] Upgrade to Nuxt 3
- [x] Switch out or upgrade @nuxtjs/svg to [nuxt-svgo](https://github.com/cpsoinos/nuxt-svgo)
- [x] Switch out nuxt-purgecss for? WindiCSS?
- [x] Upgrade to Tailwind 3
- [x] Migrate from webpack to [nuxt/vite](https://github.com/nuxt/vite) when it is ready

#### Internal TODO
- [x] Make sure posts are ascending logically
- [x] Rewrite the readme (PWA gone, store?)

**Comment by albinhubsch** [comment]
finally, the time has come for v3 🚀 🥳
