### ISSUE TITLE
'Deploy to Netlify' button is broken

### ISSUE THREAD

**Issue by hmaesta** [Knogobert/ntn-boilerplate#33]
I believe that your Github username was `knogobert` and recently to moved to `Knogobert`.
That broke all _Deploy to Netlify_ buttons, that still point to the lowercase username.

#### How to reproduce:
1. In [README.md](https://github.com/Knogobert/ntn-boilerplate/blob/master/README.md) press the _Deploy to Netlify_ button
2. Connect your Github account
3. Give the repo a random name
4. Press _Save & Deploy_

#### Places that should be fixed:
1. [Netlify docs](https://www.netlifycms.org/docs/start-with-a-template/)
2. [README.md](https://github.com/Knogobert/ntn-boilerplate/blob/master/README.md)

**Comment by Knogobert** [comment]
Good catch! Netlify must've changed case-sensitivity it looks like. Still, the main reason is my name change.

I'll make sure these two places are changed. If anyone finds another place, please tell me (except from all of your own hard forks 🤦, that's a tough one).
