### ISSUE TITLE
404 page causes articles not to load

### ISSUE THREAD

**Issue by lastlink** [Knogobert/ntn-boilerplate#4]
* navigate to https://ntn-boilerplate.netlify.app/404
* then projects or blog
  * you'll notice the articles **don't load**. 
  * if you refresh at home https://ntn-boilerplate.netlify.app then navigate to eithery you'll see the articles

**Comment by Knogobert** [comment]
Good catch! I'll look into it and fix it in version 2.0.0 or 2.0.1 that is coming soon. Thanks!

**Comment by Knogobert** [comment]
This issue is resolved by the switch to @nuxt/content. I also added a custom 404 redirect for Netlify builds now. Thanks!
