### ISSUE TITLE
Deploy to Netlify - Error

### ISSUE THREAD

**Issue by svewag** [Knogobert/ntn-boilerplate#59]
I receive this error, wenn trying to [deploy to netlify](https://www.netlifycms.org/docs/start-with-a-template/).
I tried it multiple times within the last 60 minutes.

![image](https://user-images.githubusercontent.com/155578/142608433-979d992c-ed50-4f5a-9227-67b137083598.png)

**Comment by Knogobert** [comment]
@svewag First of all, nice name ;) 
Secondly... I get the same error trying to Save & Deploy this repo. Through both GitHub and GitLab.

The weird part is that this repo is definitely existing, at that url, and set to public.
<img width="282" alt="image" src="https://user-images.githubusercontent.com/770560/142680295-f1f5df92-dd9c-4f9b-b922-da5182f6b15d.png">

Any suggestions into what this could be?

**Comment by svewag** [comment]
The error still exists. I asked for support in the [netlify forum](https://answers.netlify.com/t/netlifycms-nuxt-template-cannot-be-deployed/47714).

What does this "deploy to netlify" do? Just copying the files from this repo to a new repo?

**Comment by Knogobert** [comment]
It seems to be working again. Thanks for reaching out Sven! 
Closing this issue now
