### ISSUE TITLE
All posts date are reflecting current date even if made earlier

### ISSUE THREAD

**Issue by DjKniteX** [Knogobert/ntn-boilerplate#7]
I'm running into an issue where it looks like it works locally but once I deploy to Netlify all my post dates are for today "05/10/2021" even for the posts that I made in April and last week.

I'm expecting the last post on the page date to be 04/27/2021 instead of 05/10/2021

link: https://tcg.teamskynite.net/blog/ for reference

**Comment by Knogobert** [comment]
I added the option to blog posts to fill in a "Created Date" (it defaults to today's date). It will now overwrite the one created automatically by @nuxt/content. Which will probably break old posts if updated with this code.
