### ISSUE TITLE
'error' function in posts component is not defined

### ISSUE THREAD

**Issue by artis3n** [Knogobert/ntn-boilerplate#9]
https://github.com/Knogobert/ntn-boilerplate/blob/5e6c1b603b90fbde9ef93ad065e5067fa824a2cb/components/posts/posts.vue#L106 is returning a `ReferenceError: error is not defined` when I trigger an error on that page.

Looking at the rest of this template, every other invocation of the `error` function is wrapped inside an `asyncData` which contains an `error` function - e.g. https://github.com/Knogobert/ntn-boilerplate/blob/5e6c1b603b90fbde9ef93ad065e5067fa824a2cb/pages/projects/_project.vue#L33 . But the posts component invokes this function under `mounted` so there is no `error` function to call.

**Comment by Knogobert** [comment]
Ah, this is a mistake on my end! I think `error` doesn’t exist in components, only in nuxt pages. I'll look into this later when I find time for it, or if you've solved it somehow please put up a PR for it. Thanks for reporting!

**Comment by artis3n** [comment]
I tossed a console.error in it's place for the time being but I'll think of something more appropriate with a PR unless you get to it first :)

**Comment by Knogobert** [comment]
Thanks for reporting! 

I dug into this a bit further and decided that `.catch((err) => console.error(err) || []);` would be enough, as the real visual error reporting is triggered and shown by the `v-else` here:

https://github.com/Knogobert/ntn-boilerplate/blob/5e6c1b603b90fbde9ef93ad065e5067fa824a2cb/components/posts/posts.vue#L46-L48
